// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6d344QaKQBAIvMcCBVqPtiHcigK8cTe0',
    appId: '1:1092360223247:web:7ab814e9bc9eb82177417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    authDomain: 'chat-based-app-b3c97.firebaseapp.com',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
    measurementId: 'G-SF6R8KDKBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCikkHsQ3dBeMr09P88dJNJwU9qP22toDE',
    appId: '1:1092360223247:android:f0b2dff0a1b4e52477417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1j3rSAjcOUgEFAE1MoUe5w4vLV74inI',
    appId: '1:1092360223247:ios:6ca28f6271a6952877417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
    iosClientId: '1092360223247-uu2jrru1kv9orditm9b5ina8gbpug47g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1j3rSAjcOUgEFAE1MoUe5w4vLV74inI',
    appId: '1:1092360223247:ios:39fe276f52554f1d77417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
    iosClientId: '1092360223247-f92odiu3u0j5t4uj8m75vf00ddoi25te.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6d344QaKQBAIvMcCBVqPtiHcigK8cTe0',
    appId: '1:1092360223247:web:7ab814e9bc9eb82177417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    authDomain: 'chat-based-app-b3c97.firebaseapp.com',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
    measurementId: 'G-SF6R8KDKBN',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD6d344QaKQBAIvMcCBVqPtiHcigK8cTe0',
    appId: '1:1092360223247:web:f008a8af1a032ead77417a',
    messagingSenderId: '1092360223247',
    projectId: 'chat-based-app-b3c97',
    authDomain: 'chat-based-app-b3c97.firebaseapp.com',
    storageBucket: 'chat-based-app-b3c97.appspot.com',
    measurementId: 'G-BCCX0C9RG7',
  );
}
